print("--------------------------------")
print("Ingresa en las siguientes casillas el valor del producto y la cantidad que se va a comprar del mismo")
print("--------------------------------")
producto=int(input("Producto: "))
cantidad=int(input("Cantidad: "))
print("--------------------------------")
enunciado1=("Escogiste como valor: "+str(producto))
print(enunciado1)
enunciado2=("Escogiste como cantidad: "+str(cantidad))
print(enunciado2)
print("--------------------------------")
subtot= producto*cantidad
print("El subtotal de la compra es "+str(subtot))
print("--------------------------------")
iva=subtot*0.16
print("El iva de la compra es "+str(iva))
print("--------------------------------")   
total=(subtot+iva)
print("El total de la compra es "+str(total))
print("--------------------------------")