print("----------------------------------------------------------------")
bienv=("Hola, Introduce tú nombre, tú apellido y tú carrera en las siguientes casillas")
print(bienv)
print("----------------------------------------------------------------")
nombre=input("Introduce tu nombre: ")   
apellido=input("Introduce tu apellido: ")
carrera=input("Introduce tu carrera: ")
print("----------------------------------------------------------------")
mensaje=("Hola "+nombre+" "+apellido+", excelente que estudies "+carrera+", eres bienevnido/a" )
print(mensaje)
print("----------------------------------------------------------------")