print("-------------------------------------------------")
enunciado= ("Introduce dos números en las siguientes casillas para calcular las operaciones establecidas")
print(enunciado)
print("--------------------------------")
número1=int(input("Número 1: "))
número2=int(input("Número 2: "))
print("--------------------------------")
print(número1)
print(número2)
print("--------------------------------")
Suma= (str(int(número1+número2)))
enunciadosuma=("La suma de los números es: "+Suma+"")
print(enunciadosuma)
print("------------------------------------------------")
resta= (str(int(número1-número2)))
enunciadoresta=("La resta de los números es: "+resta+"")
print(enunciadoresta)
print("------------------------------------------------")
multiplicación= (str(int(número1*número2)))
enunciadomultiplicación=("La multiplicación de los números es: "+multiplicación+"")
print(enunciadomultiplicación)
print("------------------------------------------------")
division= (str(int(número1/número2)))
enunciadodivision=("La division de los números es: "+division+"")
print(enunciadodivision)
print("------------------------------------------------")
divisionentera=(str(int(número1//número2)))
enunciadodivisionentera=("La division entera de los números es: "+divisionentera+"")
print(enunciadodivisionentera)
print("------------------------------------------------")
modulo=(str(int(número1%número2)))
enunciadomodulo=("El modulo de los números es: "+modulo+"")
print(enunciadomodulo)
print("------------------------------------------------")
potencia=(str(int(número1**número2)))
enunciadopotencia=("La potencia de los números es: "+potencia+"")
print(enunciadopotencia)
print("------------------------------------------------")

